version: "3.6"

services:
    nginx:
        image: nginx:alpine
        container_name: bs-nginx
        working_dir: /application
        volumes:
            - .:/application:delegated
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-bs
        ports:
            - "12090:80"
    php-bs:
        environment:
            - PHP_IDE_CONFIG=serverName=localhost
        container_name: bs-php
        extra_hosts:
            - "host.docker.internal:host-gateway"
        build:
            context: ./
            dockerfile: docker/php/Dockerfile
            cache_from:
                - ./docker/php
        volumes:
            - ./:/application:delegated
    mariadb:
        image: mariadb/server:10.3
        container_name: bs-mariadb
        working_dir: /application
        environment:
            - MYSQL_ROOT_PASSWORD=business
            - MYSQL_DATABASE=business
            - MYSQL_USER=business
            - MYSQL_PASSWORD=business
        volumes:
            - sql-data:/var/lib/mysql:delegated
        ports:
            - "12092:3306"
        expose:
            - 12092
        command:
            'mysqld --innodb-flush-method=fsync --innodb-use-native-aio=0'


volumes:
    sql-data:

