version: "3.6"

services:
    nginx:
        image: nginx:alpine
        container_name: bs-nginx
        working_dir: /application
        volumes:
            - .:/application:delegated
            - ./docker/nginx/nginx.conf:/etc/nginx/conf.d/default.conf
        depends_on:
            - php-bs
        ports:
            - "12090:80"
    php-bs:
        environment:
            - PHP_IDE_CONFIG=serverName=localhost
        container_name: bs-php
        extra_hosts:
            - "host.docker.internal:host-gateway"
        build:
            context: ./
            dockerfile: docker/php/Dockerfile
            cache_from:
                - ./docker/php
        volumes:
            - ./:/application:delegated
